# permissions for end users to edit listeners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: listener-editor-role
rules:
- apiGroups:
  - debotops.hashfunc.io
  resources:
  - listeners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - debotops.hashfunc.io
  resources:
  - listeners/status
  verbs:
  - get
