# permissions for end users to view mappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mapping-viewer-role
rules:
- apiGroups:
  - debotops.hashfunc.io
  resources:
  - mappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - debotops.hashfunc.io
  resources:
  - mappings/status
  verbs:
  - get
