# permissions for end users to edit mappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mapping-editor-role
rules:
- apiGroups:
  - debotops.hashfunc.io
  resources:
  - mappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - debotops.hashfunc.io
  resources:
  - mappings/status
  verbs:
  - get
